begin;

create extension if not exists pg_net;
create extension if not exists pg_cron;

alter table public.notificacoes
  add column if not exists destino text;

create table if not exists public.entrega_ofertas (
  id bigint generated by default as identity primary key,
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  entregador_id uuid not null references public.entregadores(id) on delete cascade,
  distancia_coleta_km numeric(10,2),
  valor_oferta numeric(10,2) not null default 0,
  raio_km numeric(10,2),
  etapa smallint not null default 1,
  status text not null default 'disponivel',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pedido_id, entregador_id),
  constraint entrega_ofertas_distancia_check check (
    distancia_coleta_km is null or distancia_coleta_km between 0 and 5000
  ),
  constraint entrega_ofertas_valor_check check (
    valor_oferta between 0 and 9999.99
  ),
  constraint entrega_ofertas_raio_check check (
    raio_km is null or raio_km between 0 and 5000
  ),
  constraint entrega_ofertas_etapa_check check (etapa between 1 and 3),
  constraint entrega_ofertas_status_check check (
    status in ('disponivel','aceita','encerrada')
  )
);

create index if not exists entrega_ofertas_entregador_status_idx
  on public.entrega_ofertas(entregador_id,status,created_at desc);

create index if not exists entrega_ofertas_pedido_status_idx
  on public.entrega_ofertas(pedido_id,status);

alter table public.entrega_ofertas enable row level security;

drop policy if exists "entregador le ofertas proprias" on public.entrega_ofertas;
create policy "entregador le ofertas proprias"
on public.entrega_ofertas
for select
to authenticated
using (
  entregador_id = (select auth.uid())
  or (select private.is_admin())
);

revoke all on table public.entrega_ofertas from anon, authenticated;
grant select on table public.entrega_ofertas to authenticated;

create or replace function public.push_runtime_config()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'webhook_secret', (select v.decrypted_secret from vault.decrypted_secrets v where v.name='multi_delivery_push_webhook_secret' limit 1),
    'vapid_public', (select v.decrypted_secret from vault.decrypted_secrets v where v.name='multi_delivery_vapid_public' limit 1),
    'vapid_private', (select v.decrypted_secret from vault.decrypted_secrets v where v.name='multi_delivery_vapid_private' limit 1),
    'vapid_subject', (select v.decrypted_secret from vault.decrypted_secrets v where v.name='multi_delivery_vapid_subject' limit 1)
  );
$$;

revoke all on function public.push_runtime_config()
  from public, anon, authenticated;
grant execute on function public.push_runtime_config() to service_role;

create or replace function private.encaminhar_push_notificacao()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_project_url text;
  v_webhook_secret text;
begin
  if not exists (
    select 1
    from public.push_subscriptions ps
    where ps.usuario_id = new.usuario_id
  ) then
    return new;
  end if;

  select v.decrypted_secret into v_project_url
  from vault.decrypted_secrets v
  where v.name='multi_delivery_project_url'
  limit 1;

  select v.decrypted_secret into v_webhook_secret
  from vault.decrypted_secrets v
  where v.name='multi_delivery_push_webhook_secret'
  limit 1;

  if coalesce(v_project_url,'')='' or coalesce(v_webhook_secret,'')='' then
    return new;
  end if;

  perform net.http_post(
    url := rtrim(v_project_url,'/') || '/functions/v1/enviar-push',
    body := jsonb_build_object('record',to_jsonb(new)),
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-delivery-webhook-secret',v_webhook_secret
    ),
    timeout_milliseconds := 2500
  );

  return new;
exception
  when others then
    raise warning 'Falha ao enfileirar Web Push da notificacao %: %', new.id, SQLERRM;
    return new;
end;
$$;

revoke all on function private.encaminhar_push_notificacao()
  from public, anon, authenticated, service_role;

drop trigger if exists notificacoes_web_push on public.notificacoes;
create trigger notificacoes_web_push
after insert on public.notificacoes
for each row execute function private.encaminhar_push_notificacao();

create or replace function private.distribuir_oferta_pedido(p_pedido_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pedido record;
  v_unidade record;
  v_etapa smallint;
  v_raio numeric(10,2);
  v_limite integer;
  v_idade interval;
  v_candidato record;
  v_criadas integer := 0;
  v_distancia_txt text;
  v_ganho_txt text;
begin
  select
    p.id,p.numero,p.empresa_id,p.empresa_nome,p.unidade_id,p.pronto_em,
    p.agendado_para,p.pagamento_modalidade,p.pagamento_status,p.entregador_id
  into v_pedido
  from public.pedidos p
  where p.id=p_pedido_id
    and p.status='preparando'
    and p.pronto_em is not null
    and p.entregador_id is null
    and (p.pagamento_modalidade is distinct from 'online' or p.pagamento_status='pago')
    and (p.agendado_para is null or p.agendado_para<=now()+interval '45 minutes')
  limit 1;

  if not found then
    return 0;
  end if;

  select u.id,u.nome,u.latitude,u.longitude
  into v_unidade
  from public.empresa_unidades u
  where u.empresa_id::text=v_pedido.empresa_id::text
    and (u.id=v_pedido.unidade_id or (v_pedido.unidade_id is null and u.principal=true))
    and u.ativa=true
  order by (u.id=v_pedido.unidade_id) desc,u.principal desc
  limit 1;

  v_idade := greatest(interval '0 seconds',now()-v_pedido.pronto_em);
  if v_idade < interval '1 minute' then
    v_etapa := 1;
    v_raio := 4;
    v_limite := 5;
  elsif v_idade < interval '3 minutes' then
    v_etapa := 2;
    v_raio := 8;
    v_limite := 10;
  else
    v_etapa := 3;
    v_raio := 15;
    v_limite := 20;
  end if;

  for v_candidato in
    select
      d.id,
      coalesce(d.valor_por_entrega,0)::numeric(10,2) as valor_oferta,
      case
        when v_unidade.latitude is null or v_unidade.longitude is null then null
        else private.distancia_km(d.latitude,d.longitude,v_unidade.latitude,v_unidade.longitude)
      end as distancia_coleta_km
    from public.entregadores d
    where d.aprovado=true
      and d.online=true
      and d.latitude is not null
      and d.longitude is not null
      and d.localizacao_atualizada_em >= now()-interval '30 minutes'
      and not exists (
        select 1
        from public.pedidos px
        where px.entregador_id=d.id
          and px.status in ('preparando','saiu_para_entrega')
      )
      and (
        v_unidade.latitude is null
        or v_unidade.longitude is null
        or private.distancia_km(d.latitude,d.longitude,v_unidade.latitude,v_unidade.longitude) <= v_raio
      )
    order by
      case
        when v_unidade.latitude is null or v_unidade.longitude is null then null
        else private.distancia_km(d.latitude,d.longitude,v_unidade.latitude,v_unidade.longitude)
      end nulls last,
      d.localizacao_atualizada_em desc,
      d.id
    limit v_limite
  loop
    insert into public.entrega_ofertas(
      pedido_id,entregador_id,distancia_coleta_km,valor_oferta,raio_km,etapa,status
    )
    values (
      v_pedido.id,v_candidato.id,v_candidato.distancia_coleta_km,
      v_candidato.valor_oferta,
      case when v_unidade.latitude is null or v_unidade.longitude is null then null else v_raio end,
      v_etapa,'disponivel'
    )
    on conflict (pedido_id,entregador_id) do nothing;

    if found then
      v_distancia_txt := case
        when v_candidato.distancia_coleta_km is null then 'distância da coleta indisponível'
        else replace(to_char(v_candidato.distancia_coleta_km,'FM999990D00'),'.',',') || ' km até a coleta'
      end;
      v_ganho_txt := case
        when v_candidato.valor_oferta > 0 then
          'ganho R$ ' || replace(to_char(v_candidato.valor_oferta,'FM999999990D00'),'.',',')
        else 'tarifa ainda não configurada'
      end;

      insert into public.notificacoes(
        usuario_id,pedido_id,titulo,mensagem,tipo,lida,destino
      )
      values (
        v_candidato.id,
        v_pedido.id,
        'Nova entrega disponível',
        coalesce(v_pedido.empresa_nome,'Restaurante') || ' • ' || v_distancia_txt || ' • ' || v_ganho_txt,
        'entrega_disponivel',
        false,
        'entregador.html?oferta=' || v_pedido.id::text
      );

      v_criadas := v_criadas + 1;
    end if;
  end loop;

  return v_criadas;
end;
$$;

revoke all on function private.distribuir_oferta_pedido(uuid)
  from public, anon, authenticated, service_role;

create or replace function private.redistribuir_entregas_pendentes(p_limite integer default 100)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pedido record;
  v_total integer := 0;
begin
  for v_pedido in
    select p.id
    from public.pedidos p
    where p.status='preparando'
      and p.pronto_em is not null
      and p.entregador_id is null
      and (p.pagamento_modalidade is distinct from 'online' or p.pagamento_status='pago')
      and (p.agendado_para is null or p.agendado_para<=now()+interval '45 minutes')
    order by p.prioridade desc,p.pronto_em,p.created_at
    limit greatest(1,least(coalesce(p_limite,100),500))
  loop
    v_total := v_total + private.distribuir_oferta_pedido(v_pedido.id);
  end loop;
  return v_total;
end;
$$;

revoke all on function private.redistribuir_entregas_pendentes(integer)
  from public, anon, authenticated, service_role;

create or replace function private.sincronizar_ofertas_pedido()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_elegivel boolean;
begin
  v_elegivel :=
    new.status='preparando'
    and new.pronto_em is not null
    and new.entregador_id is null
    and (new.pagamento_modalidade is distinct from 'online' or new.pagamento_status='pago')
    and (new.agendado_para is null or new.agendado_para<=now()+interval '45 minutes');

  if v_elegivel then
    perform private.distribuir_oferta_pedido(new.id);
  else
    update public.entrega_ofertas
    set status='encerrada',updated_at=now()
    where pedido_id=new.id and status='disponivel';

    update public.notificacoes
    set lida=true
    where pedido_id=new.id
      and tipo='entrega_disponivel'
      and lida=false;
  end if;

  return new;
end;
$$;

revoke all on function private.sincronizar_ofertas_pedido()
  from public, anon, authenticated, service_role;

drop trigger if exists sincronizar_ofertas_pedido on public.pedidos;
create trigger sincronizar_ofertas_pedido
after insert or update of status,pronto_em,entregador_id,pagamento_status,pagamento_modalidade,agendado_para,unidade_id
on public.pedidos
for each row execute function private.sincronizar_ofertas_pedido();

create or replace function public.listar_entregas_disponiveis_proximidade()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_resultado jsonb;
begin
  if auth.uid() is null then
    raise exception 'Autenticação obrigatória.';
  end if;

  if not exists (
    select 1 from public.entregadores d
    where d.id=auth.uid() and d.aprovado=true and d.online=true
  ) then
    raise exception 'Entregador aprovado e online obrigatório.';
  end if;

  select coalesce(jsonb_agg(q.dados order by
    q.distancia_coleta_km nulls last,
    q.prioridade desc,
    q.ordenacao_tempo,
    q.created_at
  ),'[]'::jsonb)
  into v_resultado
  from (
    select
      p.prioridade,
      coalesce(p.agendado_para,p.created_at) as ordenacao_tempo,
      p.created_at,
      o.distancia_coleta_km,
      jsonb_build_object(
        'pedido_id',p.id,
        'numero',p.numero,
        'restaurante',p.empresa_nome,
        'unidade_id',u.id,
        'unidade_nome',coalesce(u.nome,'Unidade principal'),
        'bairro',coalesce((regexp_match(p.endereco,'— ([^—]+) —'))[1],'Região protegida'),
        'total',p.total,
        'pagamento',p.pagamento,
        'agendado_para',p.agendado_para,
        'created_at',p.created_at,
        'distancia_coleta_km',o.distancia_coleta_km,
        'distancia_entrega_km',p.distancia_km,
        'ganho_entregador',o.valor_oferta,
        'oferta_etapa',o.etapa,
        'oferta_raio_km',o.raio_km
      ) as dados
    from public.entrega_ofertas o
    join public.pedidos p on p.id=o.pedido_id
    left join lateral (
      select ux.*
      from public.empresa_unidades ux
      where ux.empresa_id::text=p.empresa_id::text
        and (ux.id=p.unidade_id or (p.unidade_id is null and ux.principal=true))
      order by (ux.id=p.unidade_id) desc,ux.principal desc
      limit 1
    ) u on true
    where o.entregador_id=auth.uid()
      and o.status='disponivel'
      and p.status='preparando'
      and p.pronto_em is not null
      and p.entregador_id is null
      and (p.pagamento_modalidade is distinct from 'online' or p.pagamento_status='pago')
      and (p.agendado_para is null or p.agendado_para<=now()+interval '45 minutes')
    limit 50
  ) q;

  return v_resultado;
end;
$$;

revoke all on function public.listar_entregas_disponiveis_proximidade()
  from public,anon,authenticated,service_role;
grant execute on function public.listar_entregas_disponiveis_proximidade()
  to authenticated;

create or replace function public.entregador_aceitar_pedido(p_pedido_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_oferta public.entrega_ofertas%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Autenticação obrigatória.';
  end if;

  if exists (
    select 1
    from public.pedidos p
    where p.entregador_id=auth.uid()
      and p.status in ('preparando','saiu_para_entrega')
  ) then
    raise exception 'Conclua sua entrega atual antes de aceitar outra.';
  end if;

  select o.* into v_oferta
  from public.entrega_ofertas o
  join public.entregadores d on d.id=o.entregador_id
  where o.pedido_id=p_pedido_id
    and o.entregador_id=auth.uid()
    and o.status='disponivel'
    and d.aprovado=true
    and d.online=true
  limit 1;

  if not found then
    raise exception 'Esta oferta não está mais disponível para você.';
  end if;

  update public.pedidos
  set entregador_id=auth.uid(),
      entregador_valor=v_oferta.valor_oferta,
      updated_at=now()
  where id=p_pedido_id
    and status='preparando'
    and pronto_em is not null
    and entregador_id is null
    and (pagamento_modalidade is distinct from 'online' or pagamento_status='pago');

  if not found then
    update public.entrega_ofertas
    set status='encerrada',updated_at=now()
    where id=v_oferta.id;
    return false;
  end if;

  update public.entrega_ofertas
  set status=case when entregador_id=auth.uid() then 'aceita' else 'encerrada' end,
      updated_at=now()
  where pedido_id=p_pedido_id;

  update public.notificacoes
  set lida=true
  where pedido_id=p_pedido_id
    and tipo='entrega_disponivel'
    and lida=false;

  return true;
end;
$$;

revoke all on function public.entregador_aceitar_pedido(uuid)
  from public,anon,authenticated,service_role;
grant execute on function public.entregador_aceitar_pedido(uuid)
  to authenticated;

create or replace function public.entregador_definir_online(p_online boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_atualizado boolean;
begin
  update public.entregadores
  set online=p_online,updated_at=now()
  where id=auth.uid() and aprovado=true;

  v_atualizado := found;
  if v_atualizado and p_online then
    perform private.redistribuir_entregas_pendentes(100);
  end if;
  return v_atualizado;
end;
$$;

revoke all on function public.entregador_definir_online(boolean)
  from public,anon,authenticated,service_role;
grant execute on function public.entregador_definir_online(boolean)
  to authenticated;

do $$
declare
  v_job bigint;
begin
  for v_job in
    select jobid from cron.job where jobname='multi-delivery-redistribuir-entregas'
  loop
    perform cron.unschedule(v_job);
  end loop;

  perform cron.schedule(
    'multi-delivery-redistribuir-entregas',
    '* * * * *',
    'select private.redistribuir_entregas_pendentes(100);'
  );
end $$;

select private.redistribuir_entregas_pendentes(100);

commit;
